# Copyright 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/precompiled_header.gni")

# Ensure precompiled headers work
precompiled_header("precompiled") {
  precompiled_header = "stdafx.h"
  precompiled_source = "stdafx.cc"
}

config("libgmp") {
  libs = []
  if (current_cpu == "x86") {
    if (is_debug) {
      libs = [
        "//src/picalc_win/libpicalc/gmp/x86/debug/gmpd.lib",
        "//src/picalc_win/libpicalc/gmp/x86/debug/gmpxxd.lib",
      ]
    } else {
      libs = [
        "//src/picalc_win/libpicalc/gmp/x86/release/gmp.lib",
        "//src/picalc_win/libpicalc/gmp/x86/release/gmpxx.lib",
      ]
    }
  } else if (current_cpu == "x64") {
    if (is_debug) {
      libs = [
        "//src/picalc_win/libpicalc/gmp/x64/debug/gmpd.lib",
        "//src/picalc_win/libpicalc/gmp/x64/debug/gmpxxd.lib",
      ]
    } else {
      libs = [
        "//src/picalc_win/libpicalc/gmp/x64/release/gmp.lib",
        "//src/picalc_win/libpicalc/gmp/x64/release/gmpxx.lib",
      ]
    }
  } else {
    assert(current_cpu != "arm64", "GMP only supported on x86 and x64!")
  }
}

# All of our Pi functions in one nice .dll
shared_library("libpicalc") {
  configs -= [ "//build/config/win:nominmax", ]
  configs += [ ":libpicalc_config" ]

  sources = [
    "component_export.h",
    "constants.h",
    "libpicalc.cc",
    "libpicalc.h",
    "libpicalc.rc"
  ]
  #deps = [ ":libpicalc_sources" ]

  public_deps = [ "//src/picalc_win/libpicalc/gmp:gmpxx" ]
}

# For no dependencies
static_library("libpicalc_static") {
  configs -= [ "//build/config/win:nominmax", ]
  configs += [ ":libpicalc_config" ]

  sources = [
    "component_export.h",
    "constants.h",
    "libpicalc.cc",
    "libpicalc.h",
    "libpicalc.rc"
  ]
  #deps = [ ":libpicalc_sources" ]

  public_deps = [ "//src/picalc_win/libpicalc/gmp:gmpxx" ]
}

source_set("libpicalc_sources") {
  configs += [ ":libpicalc_config" ]

  sources = [
    "component_export.h",
    "constants.h",
    "libpicalc.cc",
    "libpicalc.h",
    "libpicalc.rc"
  ]
}

config("libpicalc_config") {
  configs = []
  configs += [ "//src/picalc_win:nt5", ]
  # Must explicitly set this for sources
  configs += [ "//build/config/win:windowed", ]

  configs += [
    ":precompiled",
    ":libgmp"
  ]
}
