# libpicalc
# Provides a static library or dynamic .dll that exports many functions to compute Pi.
# It supports a variety of algorithms and uses the GMP library for math.

group("libpicalc_all") {
  public_deps = [
    ":libpicalc_shared",
    ":libpicalc_static",
  ]
}

group("libpicalc_shared") {
  public_deps = [ ":libpicalc" ]
}

group("libpicalc_static") {
  public_deps = [ ":static_libpicalc" ]
}

# All of our Pi functions in one nice .dll
shared_library("libpicalc") {
  defines = [ "INSIDE_DLL" ]
  configs -= [ "//build/config/win:nominmax", ]
  configs += [ ":libpicalc_config" ]

  sources = [
    "compiler_specific.h",
    "component_export.h",
    "constants.h",
    "libpicalc.cc",
    "libpicalc.h",
    "libpicalc_dll.h",
    "libpicalc.rc",
    "version.h",
  ]
  #deps = [ ":libpicalc_sources" ]

  public_deps = [
    "//src/picalc_win/libpicalc/gmp:gmp_headers",
    "//src/picalc_win/libpicalc/gmp:gmp_static"
  ]
}

# For no dependencies
static_library("static_libpicalc") {
  configs -= [ "//build/config/win:nominmax", ]
  configs += [ ":libpicalc_config" ]

  sources = [
    "compiler_specific.h",
    "component_export.h",
    "constants.h",
    "libpicalc.cc",
    "libpicalc.h",
    "libpicalc_dll.h",
    "libpicalc.rc",
    "version.h",
  ]
  #deps = [ ":libpicalc_sources" ]

  public_deps = [
    "//src/picalc_win/libpicalc/gmp:gmp_headers",
    "//src/picalc_win/libpicalc/gmp:gmp_static"
  ]
}

source_set("libpicalc_sources") {
  configs -= [ "//build/config/win:nominmax", ]
  configs += [ ":libpicalc_config" ]

  sources = [
    "compiler_specific.h",
    "component_export.h",
    "constants.h",
    "libpicalc.cc",
    "libpicalc.h",
    "libpicalc_dll.h",
    "libpicalc.rc",
    "version.h",
  ]
}

config("libpicalc_config") {
  configs = []
  # Must explicitly set this for sources
  configs += [ "//build/config/win:windowed", ]

  configs += [
    ":libpicalc_nt5",
  ]
}

config("libpicalc_nt5") {
  libs = [
    "iphlpapi.lib",
    "powrprof.lib",
    "wtsapi32.lib"
  ]
}
