import("//build/config/win/manifest.gni")
import("//build/config/static_shared.gni")

# MDI GUI App
executable("picalc_win") {
  configs -= [ "//build/config/win:console", ]
  configs -= [ "//build/config/win:nominmax", ]

  configs += [ "//build/config/win:windowed", ]

  deps = [
    ":picalc_sources",
    ":picalc_win_manifest",
  ]
}

config("nt5") {
  libs = [
    "iphlpapi.lib",
    "powrprof.lib",
    "wtsapi32.lib"
  ]
}

windows_manifest("picalc_win_manifest") {
  sources = [ as_invoker_manifest, ]

  if (use_common_controls) {
    sources += [ common_controls_manifest, ]
  }
}

source_set("picalc_sources") {
  configs -= [ "//build/config/win:nominmax", ]

  # Must explicitly set this for sources
  configs += [ "//build/config/win:windowed", ]

  configs += [ ":nt5", ]

  configs += [
    "//src/picalc_win/libpicalc:precompiled",
    "//src/picalc_win/libpicalc:libgmp"
  ]

  sources = [
    "common.h",
    "common.cc",
    "dialogs.h",
    "dialogs.cc",
    "framework.h",
    "globals.h",
    "mdi_handler.cc",
    "mdi_handler.h",
    "picalc_main.cc",
    "picalc_main.h",
    "picalc_win.rc",
    "resource.h"
  ]

  deps = []

  if (is_component_build) {
    deps += [ "//src/picalc_win/libpicalc:libpicalc" ]
  } else {
    deps += [ "//src/picalc_win/libpicalc:libpicalc_static" ]
  }
}
