# PiCalc-Win

import("//build/config/precompiled_header.gni")
import("//build/config/static_shared.gni")
import("//build/config/win/manifest.gni")

# MDI GUI Pi Calculator App
executable("picalc_win") {
  configs -= [
    "//build/config/win:console",
    "//build/config/win:nominmax",
  ]

  configs += [
    "//build/config/win:windowed",
    ":picalc_nt5",
  ]

  deps = [
    ":picalc_sources",
    ":picalc_win_manifest",
  ]
}

# Precompiled header for common C/C++ stdlib stuff
precompiled_header("precompiled") {
  precompiled_header = "stdafx.h"
  precompiled_source = "stdafx.cc"
}

source_set("picalc_sources") {
  configs -= [ "//build/config/win:nominmax", ]

  # Must explicitly set this for sources
  configs += [ "//build/config/win:windowed", ]

  configs += [
    ":picalc_nt5",
    ":precompiled"
  ]

  sources = [
    "common.h",
    "common.cc",
    "dialogs.h",
    "dialogs.cc",
    "framework.h",
    "globals.h",
    "mdi_handler.cc",
    "mdi_handler.h",
    "picalc_main.cc",
    "picalc_main.h",
    "picalc_test.cc",
    "picalc_win.rc",
    "resource.h"
  ]

  deps = []

  if (is_component_build) {
    deps += [
      "//src/picalc_win/libpicalc:libpicalc_shared"
    ]
  } else {
    deps += [
      "//src/picalc_win/libpicalc:libpicalc_static"
    ]
  }
}

# Libs to support NT 5.x
config("picalc_nt5") {
  libs = [
    "iphlpapi.lib",
    "powrprof.lib",
    "wtsapi32.lib"
  ]
}

windows_manifest("picalc_win_manifest") {
  sources = [ as_invoker_manifest ]

  if (use_common_controls) {
    sources += [ common_controls_manifest, ]
  }
}

group("picalc_test") {
  testonly = true
  deps = [ "//src/picalc_win/libpicalc:libpicalc_all" ]
}
