// Copyright (c) 2011 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Precompiled header generator for Windows builds. Simply provides a compilation unit for the
// header file.

// No include is needed in this file as the PCH include is forced via the "Forced Include File"
// flag in the projects generated by GYP/GN.
